#.streamlit/secrets.toml 
#database infomation
#ref: https://docs.streamlit.io/develop/tutorials/databases/mssql


server = "localhost"
database = "Event_database"
username = "sa"
password = "<your database password>"
